#!/bin/bash

# fill it
pkgname=mate-desktop
pkgver=0.0.0-1
pkgdesc="Library with common API for various MATE modules"
#depends="mate-conf, startup-notification, gtk2"
# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf ${pkgname}.tar.gz
	# entramos a la carpeta
	cd ${pkgname}
	
	./configure --prefix=/usr --sysconfdir=/etc \
		--localstatedir=/var --disable-static \
		--with-mate-distributor="Mate for Debian Build Script MDBS" \
		--disable-scrollkeeper
	make
	make DESTDIR="$pkgdir" install
	
	# prevent conflicts errors
	mv "${pkgdir}/usr/share/omf" "${pkgdir}/usr/share/mate-omf"
	rm "${pkgdir}/usr/share/pixmaps/apple-green.png"
	rm "${pkgdir}/usr/share/pixmaps/apple-red.png"
	rm "${pkgdir}/usr/share/pixmaps/gtkvim.png"
	rm "${pkgdir}/usr/share/pixmaps/kterm.xpm"
	rm "${pkgdir}/usr/share/pixmaps/monitor.png"
	rm "${pkgdir}/usr/share/pixmaps/vnterm.xpm"
}

# esto incluye la parte que se repite en la mayoria de los builds
. ../common
