.TH "MateComponent Activation Server" "1"
.SH "NAME"
.LP
matecomponent-activation-server \- MATE component tracker
.SH "DESCRIPTION"
.LP
This application tracks information about installed components and brokers
components, in conjunction with its client library; libmatecomponent-activation.

It reads the component descriptions from ${prefix}/lib/matecomponent/servers/*.server.
These files provide an XML description of a components capabilities which can be
queried and manipulated by clients from the client library.

MateComponent-activation-server also ensures that the minimum neccessary number of
servers for your display setup are running.

MateComponent-activation-server executes all components with the environment inherited
from the first process to start the server. In addition to using your prefix,
it will examine the MATECOMPONENT_ACTIVATION_PATH and the MATE2_PATH environment
variables to find .server files.

In addition it examines an XML configuration file in ${prefix}/etc/matecomponent-activation/matecomponent-activation-config.xml

For more information see \fBhttp://www.gnome.org\fR.
