#!/bin/bash

# fill it
pkgname=mate-themes
pkgver=2011.9.26
pkgrel=1
pkgdesc="Default themes for the MATE desktop"
#depends="gtk2, gtk-engines"
# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf download
	# entramos a la carpeta
	cd ${pkgname}

	./configure --prefix=/usr --enable-all-themes \
		--disable-placeholders || return 1
	make || return 1
    make DESTDIR="$pkgdir" install || return 1
}

# esto incluye la parte que se repite en la mayoria de los builds
. /usr/share/mate-doc-utils/mate-debian.sh
