#!/bin/bash

# fill it
pkgname=mate-icon-theme
pkgver=2011.10.29
pkgrel=1
pkgdesc="MATE icon theme"
#depends="hicolor-icon-theme, icon-naming-utils, gtk-update-icon-cache"

# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf download
	# entramos a la carpeta
	cd ${pkgname}

	./configure --prefix=/usr
	make
    make DESTDIR="${pkgdir}" install
    #don't include icon cache
    rm -f  "${pkgdir}/usr/share/icons/mate/icon-theme.cache"
}

# esto incluye la parte que se repite en la mayoria de los builds
. /usr/share/mate-doc-utils/mate-debian.sh
