#!/bin/bash

# fill it
pkgname=mate-polkit
pkgver=0.0.0-1
pkgdesc="PolicyKit integration for the MATE desktop"
#depends="polkit, gtk2"
# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf ${pkgname}.tar.gz
	# entramos a la carpeta
	cd ${pkgname}

	./configure --prefix=/usr --sysconfdir=/etc \
		--localstatedir=/var --libexecdir=/usr/lib/polkit-mate \
		--disable-static
	make
	make DESTDIR="${pkgdir}" install
	install -Dm644 "${srcdir}/polkit-mate-authentication-agent-1.desktop" \
		"${pkgdir}/etc/xdg/autostart/polkit-mate-authentication-agent-1.desktop"
}

# esto incluye la parte que se repite en la mayoria de los builds
. ../common
