#!/bin/bash

# fill it
pkgname=mate-desktop-environment
pkgver=0.0.0-1
pkgdesc="Common libraries for MATE"

# editar esta funcion!
build() {
	return 0
}

# esto incluye la parte que se repite en la mayoria de los builds
. ../common
