pkgname=mate-bluetooth

post_install() {
	usr/sbin/mateconfpkg --install ${pkgname}
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

pre_upgrade() {
	pre_remove $1
}

post_upgrade() {
	post_install $1
}

pre_remove() {
	if [ -f usr/share/mateconf/schemas/${pkgname}.schemas ]; then
		usr/sbin/mateconfpkg --uninstall ${pkgname}
	fi
}

post_remove() {
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}
