.\"     Title: mate-gsettings-data-convert
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 05/05/2010
.\"    Manual: User Commands
.\"    Source: User Commands
.\"
.TH "GSETTINGS\-DATA\-CON" "1" "05/05/2010" "User Commands" "User Commands"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
mate-gsettings-data-convert \- MateConf to GSettings data migration
.SH "SYNOPSIS"
.HP 23
\fBgsettings\-data\-convert\fR [option...]
.SH "DESCRIPTION"
.PP

\fBgsettings\-data\-convert\fR
reads values out of the users MateConf database and stores them in GSettings\&.
.PP
The information about the mapping from MateConf keys to GSettings keys is taken from files in
\fI/usr/share/MateConf/gsettings\fR\&. Each file in that directory is read as a key file, with sections for each GSettings schema that is being converted\&. The entries in each section map GSettings keys to paths in the MateConf database\&. Currently,
\fBgsettings\-data\-convert\fR
supports all basic MateConf types as well as lists of strings and lists of integers\&.
.PP
A simple example might look like this:
.sp
.RS 4
.nf
[org\&.mate\&.fonts]
antialiasing = /desktop/mate/font_rendering/antialiasing
dpi = /desktop/mate/font_rendering/dpi
hinting = /desktop/mate/font_rendering/hinting
rgba_order = /desktop/mate/font_rendering/rgba_order
.fi
.RE
.PP
If the GSettings schema does not have a fixed path, you must specify the path in the group name, separated by a colon character:
.sp
.RS 4
.nf
[org\&.mate\&.fonts:/desktop/mate/font\-rendering/]
.fi
.RE
.PP

\fBgsettings\-data\-convert\fR
keeps a list of the key files it has already converted, so it is safe to run it repeatedly to handle newly appeared key files\&. The expected use of this utility is to make each application install a key file for the MateConf keys that it wants to be migrated, and run
\fBgsettings\-data\-convert\fR
every time a user logs in\&.
.SS "Options"
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print help and exit
.RE
.PP
\fB\-\-dry\-run\fR
.RS 4
Do not make any changes, just report what would be done
.RE
.PP
\fB\-\-verbose\fR
.RS 4
Show verbose messages
.RE
.SH "SEE ALSO"
.PP

\fBmate-gsettings-schema-convert\fR(1)
is a related command that helps with the conversion of schemas from MateConf to GSettings\&.
