.\" Copyright (C) 2004 Andre Lehovich <andrel@u.arizona.edu>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License 
.\" along with this; if not write to the Free Software Foundation, Inc.
.\" 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA
.TH totem 1 "2008\-08\-25" "MATE"
.SH NAME
Totem \- MATE desktop movie player based on GStreamer
.SH SYNOPSIS
.B totem
.RI [ option... ] " " [ filenames | URI ]
.SH DESCRIPTION
.B Totem
is a movie player for the MATE desktop.  Through use of the
.B GStreamer
backend many popular file and streaming formats are supported including:
MPEG audio and video (MP3/MPV), Ogg, AVI, ASF, MOV, WMV,
QuickTime, and more.  Playing of DVD and VCD media is
also possible.
Although primarily intended as a movie player,
.B Totem
can also play many audio formats.
.P
For additional documentation on interactive use of 
.B Totem
select the
.I Help
menu option.  The menus allow access to some features not
available through keybindings or command-line options.
.SH OPTIONS
.TP
.B \-?, --help
Output a longer help message then quit.  (Any discrepancies
between this man page and the output of
.B totem --help
should be reported as a documentation bug.)
.TP
.B --version
Output version information then quit.
.P
The following options command an already-running instance of
.B Totem
to do something; they are useful for remote-control scripting. If 
.B Totem
is not already running, these commands will launch a new instance of
.B Totem
but will not do anything further.
.TP
.B --play-pause
Tell an already-running instance of 
.B Totem
to toggle between play and pause.
.TP
.B --play
Tell an already-running instance of
.B Totem
to play (has no effect if already playing)
.TP
.B --pause
Tell an already-running instance of
.B Totem
to pause (has no effect if already paused)
.TP
.B --next
Tell an already-running instance of 
.B Totem
to skip to the next movie or chapter in the playlist.
.TP
.B --previous
Tell an already-running instance of 
.B Totem
to return to the previous movie or chapter in the playlist.
.TP
.B --seek-fwd
Tell an already-running instance of 
.B Totem
to seek forwards 15 seconds in the current movie.
.TP
.B --seek-bwd
Tell an already-running instance of 
.B Totem
to seek backwards 15 seconds in the current movie.
.TP
.B --volume-up
Tell an already-running instance of 
.B Totem
to raise the volume by 8%.
.TP
.B --volume-down
Tell an already-running instance of 
.B Totem
to lower the volume by 8%.
.TP
.B --fullscreen
Tell an already-running instance of 
.B Totem
to toggle fullscreen mode.
.TP
.B --toggle-controls
Tell an already-running instance of
.B Totem
to toggle showing the controls.
.TP
.B --quit
Tell an already-running instance of
.B Totem
to quit.
.TP
.BI "--enqueue " filename|URI
Tell an already-running instance of Totem to add a new stream
to the playlist.
.TP
.BI "--replace " filename|URI
Tell an already-running instance of Totem to play 
from the playlist.
.SH KEYBINDINGS
Global keybindings for
.BR Totem :
.P
.ta \w'Down-arrow   'u	
a	cycle between aspect ratios
.br
p	toggle between play and pause
.br
Esc	exit full screen mode
.br
f	toggle full screen
.br
h	toggle display of on-screen controls
.br
0	resize window to 50% original size
.br
1	resize window to 100% original size
.br
2	resize window to 200% original size
.br
.br
r	zoom in the video
.br
t	zoom out the video
.br
d	start and stop the telestrator (drawing) mode
.br
e	erase the drawing
.br
Left-arrow        skip back 15 seconds
.br
Right-arrow       skip forward 60 seconds
.br
Shift+Left-arrow  skip back 5 seconds
.br
Shift+Right-arrow skip forward 15 seconds
.br
Ctrl+Left-arrow   skip back 3 minutes
.br
Ctrl+Right arrow  skip forward 10 minutes
.br
Up-arrow	increase volume by 8%
.br
Down-arrow	decrease volume by 8%
.br
b		jump back to previous chapter/movie in playlist
.br
n		jump to next chapter/movie in playlist
.br
q		quit
.br
Ctrl+E          eject the playing optical media
.br
Ctrl+O		open a new file
.br
Ctrl+L		open a new URI
.br
F9		toggle display of the playlist
.br
m		show the DVD menu
.br
c		show the DVD chapter menu
.SH FILES
.I /usr/lib/totem/plugins/
.RS
The global plugins directory, which contains all the system-installed
plugins.
.RE
.I ~/.local/share/totem/plugins/
.RS
The user plugins directory, containing plugins available only to that user.
It is always in the "totem/plugins" subdirectory of your 
.B XDG_DATA_HOME
directory.
.RE
.I ~/.config/totem/state.ini
.RS
The configuration file for the main window's appearance, stored in a
simple INI format.
.RE
.SH BUGS
.B Totem
cannot play files using some proprietary codecs.
.SH AUTHOR
.B Totem
was written by Bastien Nocera <hadess@hadess.net>.
This manual page was written by Andre Lehovich for the
Debian Project.
.SH DISTRIBUTION
The latest version of Totem may be downloaded from
.UR http://projects.mate.org/totem/
<http://projects.mate.org/totem/>
.UE
.SH SEE ALSO
.BR "totem-video-thumbnailer" (1),
.P
The online documentation available through the program's
.I Help
menu.
