#!/bin/bash

# fill it
pkgname=mate-polkit
pkgver=2011.10.29
pkgrel=1
pkgdesc="PolicyKit integration for the MATE desktop"
#depends="polkit, gtk2"
# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf download
	# entramos a la carpeta
	cd ${pkgname}

	./configure --prefix=/usr --sysconfdir=/etc \
		--localstatedir=/var --libexecdir=/usr/lib/polkit-mate \
		--disable-static
	make
	make DESTDIR="${pkgdir}" install
}

# esto incluye la parte que se repite en la mayoria de los builds
. /usr/share/mate-doc-utils/mate-debian.sh
