.\" Copyright (c) 1987-2008 - Sun Microsystems, Inc.
.TH GCALCTOOL 1 "17 June 2009"
.SH NAME
gcalctool \- a desktop calculator
.SH SYNOPSIS
.B gcalctool
[
.I OPTION
] ...
.SH DESCRIPTION
.B gcalctool
is the official calculator of the MATE desktop environment.
.SH OPTIONS
.TP
.B \-s, \-\-solve
Solve the equation provided following this option.
.TP
.B \-u, \-\-unittest
Run the unit tests.
.TP
.B \-v, \-\-version
Output version information and exit.
.TP
.B \-h, \-?, \-\-help
Prints the command line options.
.SH FILES
.PD 0
.TP 18
.B ~/.gcalctoolrc
user's personal gcalctool resources for customizing the appearance and color of
.B gcalctool
.sp
.LP
