#!/bin/bash

# fill it
pkgname=mate-dialogs
pkgver=2011.10.29
pkgrel=1
pkgdesc="Display graphical dialog boxes from shell scripts"
#depends="libmatenotify"
# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf download
	# entramos a la carpeta
	cd ${pkgname}

	./configure --prefix=/usr --sysconfdir=/etc \
		--localstatedir=/var --disable-scrollkeeper
	make
	make DESTDIR="${pkgdir}" install
	# hax!

	#ln -s matedialog ${pkgdir}/usr/bin/zenity
	rm ${pkgdir}/usr/bin/gdialog
}

# esto incluye la parte que se repite en la mayoria de los builds
. /usr/share/mate-doc-utils/mate-debian.sh
