/*
 * The MateComponent Document Model
 *
 * Author: 
 *     Miguel de Icaza (miguel@gnu.org)
 *
 */
#ifndef _MATECOMPONENT_IDL_INCLUDED_
#define _MATECOMPONENT_IDL_INCLUDED_

#ifndef __MateComponent_COMPILATION
#ifdef __MATECORBA_IDL__
%{
#pragma include_defs matecomponent/MateComponent.h
%}
#pragma inhibit push
#endif
#endif

/* From matecomponent-activation */
#include <MateComponent_Unknown.idl>
#include <MateComponent_GenericFactory.idl>

/* Basics */
#include <MateComponent_Exception.idl>
#include <MateComponent_Moniker.idl>
#include <MateComponent_Context.idl>

/* Storage stuff. */
#include <MateComponent_Storage.idl>
#include <MateComponent_Persist.idl>

/* Control stuff. */
#include <MateComponent_Listener.idl>
#include <MateComponent_Gdk.idl>
#include <MateComponent_UI.idl>
#include <MateComponent_Property.idl>
#include <MateComponent_Control.idl>
#include <MateComponent_Zoomable.idl>

/* Subdocument stuff. */
#include <MateComponent_ItemContainer.idl>
#include <MateComponent_Canvas.idl>
#include <MateComponent_Embeddable.idl>

/* Printing stuff */
#include <MateComponent_Print.idl>

/* Clipboard */
#include <MateComponent_Clipboard.idl>

#include <MateComponent_Application.idl>

#ifndef __MateComponent_COMPILATION
#ifdef __MATECORBA_IDL__
#pragma inhibit pop
#endif
#endif
#endif /* _MATECOMPONENT_IDL_INCLUDED_ */
