#!/bin/bash

# fill it
pkgname=mate-display-manager
pkgver=0.0.0-1
pkgdesc="The MATE Display Manager"
#depends="pam, libdmx, tcp_wrappers, mate-panel, libmatecanvas, librsvg, gksu, dbus-glib, consolekit, mate-dialogs"
# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf ${pkgname}.tar.gz
	# entramos a la carpeta
	cd ${pkgname}
	
	./configure --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib/gdm \
		--localstatedir=/var --disable-static \
		--with-at-spi-registryd-directory=/usr/lib/at-spi \
		--disable-scrollkeeper || return 1

	make
	make MATECONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=1 DESTDIR="${pkgdir}" install
	install -m755 -d "${pkgdir}/usr/share/mateconf/schemas"
	mateconf-merge-schema "${pkgdir}/usr/share/mateconf/schemas/${pkgname}.schemas" --domain ${pkgname} ${pkgdir}/etc/mateconf/schemas/*.schemas
	rm -f ${pkgdir}/etc/mateconf/schemas/*.schemas

	install -m644 "${srcdir}/gdm.pam" "${pkgdir}/etc/pam.d/gdm"
	install -m644 "${srcdir}/gdm-autologin.pam" "${pkgdir}/etc/pam.d/gdm-autologin"

	install -m755 -d "${pkgdir}/etc/rc.d"
	install -m755 "${srcdir}/gdm" "${pkgdir}/etc/rc.d/"

	rmdir "${pkgdir}/var/gdm"
	chmod 1770 "${pkgdir}/var/log/gdm"
	rm -rf "${pkgdir}/var/run"
}

# esto incluye la parte que se repite en la mayoria de los builds
. ../common
