pkgname=mate-control-center

post_install() {
	usr/sbin/mateconfpkg --install ${pkgname}
	update-desktop-database -q
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
	update-mime-database usr/share/mime
}

pre_upgrade() {
	pre_remove $1
}

post_upgrade() {
	post_install $1
}

pre_remove() {
	usr/sbin/mateconfpkg --uninstall ${pkgname}
}

post_remove() {
	update-desktop-database -q
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
	update-mime-database usr/share/mime
}
