#!/bin/bash

# fill it, edit "control" file  too
pkgname=libmatecomponent
pkgver=2011.10.29
pkgrel=1
pkgdesc="A set of language and system independant CORBA interfaces for creating reusable components"
depends=('mate-corba')
makedepends=('flex' 'libpopt-dev' 'bison' 'libmatecomponent' 'libglib2.0-dev')

# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf download
	# entramos a la carpeta
	cd ${pkgname}

	./configure --prefix=/usr --sysconfdir=/etc \
		--localstatedir=/var --disable-static \
		--libexecdir=/usr/lib/matecomponent || return 1
	make || return 1
	make DESTDIR="${pkgdir}" install
	install -m644 "${srcdir}/matecomponent-activation-config.xml" "${pkgdir}/etc/matecomponent-activation/"
}

# esto incluye la parte que se repite en la mayoria de los builds
. /usr/share/mate-doc-utils/mate-debian.sh
