#!/bin/bash

# fill it
pkgname=mate-panel
pkgver=0.0.0-1
pkgdesc="The MATE Panel"
#depends="libwnck, mate-conf, mate-menus, mate-desktop, librsvg, hicolor-icon-theme, libcanberra, libmatecomponentui, libmateweather"

# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf ${pkgname}.tar.gz
	# entramos a la carpeta
	cd ${pkgname}
	
	./configure --prefix=/usr --sysconfdir=/etc \
		--localstatedir=/var --disable-static \
		--libexecdir=/usr/lib/${pkgname} \
		--disable-scrollkeeper || return 1
	make || return 1
	make MATECONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=1 DESTDIR="${pkgdir}" install || return 1

	install -m755 -d "${pkgdir}/usr/share/mateconf/schemas"
	mateconf-merge-schema "${pkgdir}/usr/share/mateconf/schemas/${pkgname}.schemas" --domain ${pkgname} ${pkgdir}/etc/mateconf/schemas/*.schemas || return 1
	rm -f ${pkgdir}/etc/mateconf/schemas/*.schemas
}

# esto incluye la parte que se repite en la mayoria de los builds
. ../common
