#!/bin/bash

# fill it
pkgname=mate-settings-daemon
pkgver=2011.10.29
pkgrel=1
pkgdesc="Common libraries for MATE"
depends=('libmatekbd' 'mate-desktop' 'libmatenotify' 'hicolor-icon-theme')

# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf download
	# entramos a la carpeta
	cd ${pkgname}

	./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var \
		--libexecdir=/usr/bin/${pkgname} \
		--disable-static --disable-pulse --disable-schemas-install \
		--enable-polkit || return 1
	make || return 1

	make DESTDIR="${pkgdir}" MATECONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=1 install || return 1

	install -d -m755 "${pkgdir}/usr/share/mateconf/schemas"
	mateconf-merge-schema "${pkgdir}/usr/share/mateconf/schemas/${pkgname}.schemas" --domain ${pkgname} ${pkgdir}/etc/mateconf/schemas/*.schemas || return 1
	rm -f ${pkgdir}/etc/mateconf/schemas/*.schemas
}

# esto incluye la parte que se repite en la mayoria de los builds
. /usr/share/mate-doc-utils/mate-debian.sh
