#!/bin/bash

# fill it
pkgname=mate-devel-docs
pkgver=0.0.0-1
pkgdesc="Developer documentation for MATE"
#depends="libxslt, python2, docbook-xml, rarian"

# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf ${pkgname}.tar.gz
	# entramos a la carpeta
	cd ${pkgname}
	
	./configure --prefix=/usr --sysconfdir=/etc \
		--mandir=/usr/share/man --localstatedir=/var --disable-scrollkeeper
	make
    make DESTDIR="$pkgdir" install || return 1
}

# esto incluye la parte que se repite en la mayoria de los builds
. ../common
