#!/bin/sh

pkgname=mate-session-manager

getent group gdm >/dev/null 2>&1 || groupadd -g 120 gdm
getent passwd gdm > /dev/null 2>&1 || /usr/sbin/useradd -c 'MATE Display Manager' -u 120 -g gdm -d /var/lib/gdm -s /sbin/nologin gdm
passwd -l gdm > /dev/null
chown -R gdm:gdm /var/lib/gdm > /dev/null

gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
mateconfpkg --install ${pkgname}

exit 0
