#!/bin/sh

pkgname=mate-session-manager

getent group mdm >/dev/null 2>&1 || groupadd -g 120 mdm
getent passwd mdm > /dev/null 2>&1 || /usr/sbin/useradd -c 'MATE Display Manager' -u 120 -g mdm -d /var/lib/mdm -s /sbin/nologin mdm
passwd -l mdm > /dev/null
chown -R mdm:mdm /var/lib/mdm > /dev/null

gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
mateconfpkg --install ${pkgname}

exit 0
