#!/bin/sh

pkgname=mate-file-manager

/usr/sbin/mateconfpkg --install ${pkgname}
gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor

update-desktop-database -q

update-mime-database /usr/share/mime > /dev/null

exit 0
