#!/bin/bash

# fill it
pkgname=mate-extract
pkgver=0.0.0-1
pkgdesc="Archive manipulator for MATE"
#depends="desktop-file-utils, mate-conf, hicolor-icon-theme"
# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf ${pkgname}.tar.gz
	# entramos a la carpeta
	cd ${pkgname}
	
	mate-doc-prepare --force
	autoreconf -i
	aclocal
	
	./configure --prefix=/usr \
		--disable-static \
		--localstatedir=/var \
		--libexecdir=/usr/lib/${pkgname} \
		--disable-scrollkeeper \
		--disable-schemas-install \
		--sysconfdir=/etc \
		--disable-packagekit
	make
	make MATECONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=1 DESTDIR="$pkgdir/" install
	install -d -m755 "${pkgdir}/usr/share/mateconf/schemas"
	mateconf-merge-schema "${pkgdir}/usr/share/mateconf/schemas/*.schemas" --domain "${pkgname}" "${pkgdir}/etc/mateconf/schemas/*.schemas"
	rm -f "${pkgdir}/etc/mateconf/schemas/*.schemas"
}

# esto incluye la parte que se repite en la mayoria de los builds
. ../common
