#!/bin/bash

# fill it
pkgname=libmatekeyring
pkgver=0.0.0-1
pkgdesc="MATE keyring client library"
#depends="libgcrypt, mate-keyring"
# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf ${pkgname}.tar.gz
	# entramos a la carpeta
	cd ${pkgname}
	
	./configure --prefix=/usr --sysconfdir=/etc \
		--localstatedir=/var --disable-static \
		--libexecdir=/usr/lib/mate-keyring || return 1

	make || return 1
    make DESTDIR="${pkgdir}" install || return 1
}

# esto incluye la parte que se repite en la mayoria de los builds
. ../common
