.\" mate-options.7 - Standard Command Line Options for Mate Programs
.\" Copyright 2002, 2003  Jochen Voss <voss@debian.org>
.\" You may redistribute and modify this manual page
.\" under the terms of the GPL.
.TH mate-options 7 "2003-10-20" "MATE 2.2" "Mate User's Manual"
.SH NAME
mate-options \- Standard Command Line Options for MATE 2 Programs
.SH SYNOPSIS
.IR "program " [ "standard options" "] [" "specific options" "] " arguments
.SH DESCRIPTION
This manual page describes the command line options, which are common
to all Mate applications.
.SH OPTIONS
.SS Help options
.TP
\fB-?\fR, \fB\-\-help\fR
Show the applications help message.
.TP
\fB\-\-usage\fR
Display a brief usage message.
.TP
\fB\-\-version\fR
Show the applications's version information.
.SS MateComponent Activation support
.TP
\fB\-\-oaf\-ior\-fd\fR=\fIFD\fR
File descriptor to print IOR on
.TP
\fB\-\-oaf\-activate\-iid\fR=\fIIID\fR
IID to activate
.TP
\fB\-\-oaf\-private\fR
Prevent registering of server with OAF
.SS MATE library options
.TP
\fB\-\-disable\-sound\fR
Disable sound server usage
.TP
\fB\-\-enable\-sound\fR
Enable sound server usage
.TP
\fB\-\-espeaker\fR=\fIHOSTNAME\fR:PORT
.IR Host : port
on which the
.B esd
sound server to use is running.  This is useful if you simultaneously
run programs on several machines.
.SS MATE GUI options
.TP
\fB\-\-disable\-crash\-dialog\fR
Disable the crash dialog, which is normally shown when the application
segfaults.
.SS Session management options
.TP
\fB\-\-sm\-client\-id\fR=\fIID\fR
Specify session management ID.  Only used by the session manager itself
while restarting the application.
.TP
\fB\-\-sm\-config\-prefix\fR=\fIPREFIX\fR
Specify prefix of saved configuration.
.TP
\fB\-\-sm\-disable\fR
Disable connection to session manager.
.SS Other options
.TP
\fB\-\-load\-modules\fR=\fIMODULE1\fR,MODULE2,...
Dynamic modules to load
.SH "SEE ALSO"

For most MATE programs there will be additional command line options,
which are specific to the program.  These will be explained in the
.I Application options
section of the
.I --help
output and in the application's online help.
.SH AUTHOR
This manual page was written by Jochen Voss <voss@debian.org>.  A
first version was generated with the help of the
.I help2man
program.  The program's output was manually edited later.
