#!/bin/bash

# fill it
pkgname=mate-conf
pkgver=2011.10.29
pkgrel=1
pkgdesc="A configuration database system"
depends=('mate-corba')
#"mate-corba, libxml2, polkit, libldap, dbus-glib, gtk2"
makedepends=('libdbus-1-dev' 'libdbus-glib-1-dev' 'libpolkit-backend-1-dev')


# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf download
	# entramos a la carpeta
	cd ${pkgname}

	./configure --prefix=/usr --sysconfdir=/etc \
		--libexecdir=/usr/lib/MateConf \
		--localstatedir=/var \
		--enable-defaults-service --enable-gsettings-backend=no || return 1
	make || return 1

	make DESTDIR="${pkgdir}" install || return 1
	install -m755 -d "${pkgdir}/etc/mateconf/mateconf.xml.system" || return 1
	install -m755 "${srcdir}/mateconf-merge-schema" "${pkgdir}/usr/bin/" || return 1
	install -d -m755 "${pkgdir}/usr/sbin"
	install -m755 "${srcdir}/mateconfpkg" "${pkgdir}/usr/sbin/" || return 1
}

# esto incluye la parte que se repite en la mayoria de los builds
. /usr/share/mate-doc-utils/mate-debian.sh
