/* unicode-blocks.h */
/* THIS IS A GENERATED FILE. CHANGES WILL BE OVERWRITTEN. */
/* Generated by ./gen-guch-unicode-tables.pl */
/* Generated from UCD version 5.2.0 */

#ifndef UNICODE_BLOCKS_H
#define UNICODE_BLOCKS_H

#include <glib.h>
#include <glib/gi18n-lib.h>

/* for extraction by intltool */
#if 0
  N_("Basic Latin"),
  N_("Latin-1 Supplement"),
  N_("Latin Extended-A"),
  N_("Latin Extended-B"),
  N_("IPA Extensions"),
  N_("Spacing Modifier Letters"),
  N_("Combining Diacritical Marks"),
  N_("Greek and Coptic"),
  N_("Cyrillic"),
  N_("Cyrillic Supplement"),
  N_("Armenian"),
  N_("Hebrew"),
  N_("Arabic"),
  N_("Syriac"),
  N_("Arabic Supplement"),
  N_("Thaana"),
  N_("N'Ko"),
  N_("Samaritan"),
  N_("Devanagari"),
  N_("Bengali"),
  N_("Gurmukhi"),
  N_("Gujarati"),
  N_("Oriya"),
  N_("Tamil"),
  N_("Telugu"),
  N_("Kannada"),
  N_("Malayalam"),
  N_("Sinhala"),
  N_("Thai"),
  N_("Lao"),
  N_("Tibetan"),
  N_("Myanmar"),
  N_("Georgian"),
  N_("Hangul Jamo"),
  N_("Ethiopic"),
  N_("Ethiopic Supplement"),
  N_("Cherokee"),
  N_("Unified Canadian Aboriginal Syllabics"),
  N_("Ogham"),
  N_("Runic"),
  N_("Tagalog"),
  N_("Hanunoo"),
  N_("Buhid"),
  N_("Tagbanwa"),
  N_("Khmer"),
  N_("Mongolian"),
  N_("Unified Canadian Aboriginal Syllabics Extended"),
  N_("Limbu"),
  N_("Tai Le"),
  N_("New Tai Lue"),
  N_("Khmer Symbols"),
  N_("Buginese"),
  N_("Tai Tham"),
  N_("Balinese"),
  N_("Sundanese"),
  N_("Lepcha"),
  N_("Ol Chiki"),
  N_("Vedic Extensions"),
  N_("Phonetic Extensions"),
  N_("Phonetic Extensions Supplement"),
  N_("Combining Diacritical Marks Supplement"),
  N_("Latin Extended Additional"),
  N_("Greek Extended"),
  N_("General Punctuation"),
  N_("Superscripts and Subscripts"),
  N_("Currency Symbols"),
  N_("Combining Diacritical Marks for Symbols"),
  N_("Letterlike Symbols"),
  N_("Number Forms"),
  N_("Arrows"),
  N_("Mathematical Operators"),
  N_("Miscellaneous Technical"),
  N_("Control Pictures"),
  N_("Optical Character Recognition"),
  N_("Enclosed Alphanumerics"),
  N_("Box Drawing"),
  N_("Block Elements"),
  N_("Geometric Shapes"),
  N_("Miscellaneous Symbols"),
  N_("Dingbats"),
  N_("Miscellaneous Mathematical Symbols-A"),
  N_("Supplemental Arrows-A"),
  N_("Braille Patterns"),
  N_("Supplemental Arrows-B"),
  N_("Miscellaneous Mathematical Symbols-B"),
  N_("Supplemental Mathematical Operators"),
  N_("Miscellaneous Symbols and Arrows"),
  N_("Glagolitic"),
  N_("Latin Extended-C"),
  N_("Coptic"),
  N_("Georgian Supplement"),
  N_("Tifinagh"),
  N_("Ethiopic Extended"),
  N_("Cyrillic Extended-A"),
  N_("Supplemental Punctuation"),
  N_("CJK Radicals Supplement"),
  N_("Kangxi Radicals"),
  N_("Ideographic Description Characters"),
  N_("CJK Symbols and Punctuation"),
  N_("Hiragana"),
  N_("Katakana"),
  N_("Bopomofo"),
  N_("Hangul Compatibility Jamo"),
  N_("Kanbun"),
  N_("Bopomofo Extended"),
  N_("CJK Strokes"),
  N_("Katakana Phonetic Extensions"),
  N_("Enclosed CJK Letters and Months"),
  N_("CJK Compatibility"),
  N_("CJK Unified Ideographs Extension A"),
  N_("Yijing Hexagram Symbols"),
  N_("CJK Unified Ideographs"),
  N_("Yi Syllables"),
  N_("Yi Radicals"),
  N_("Lisu"),
  N_("Vai"),
  N_("Cyrillic Extended-B"),
  N_("Bamum"),
  N_("Modifier Tone Letters"),
  N_("Latin Extended-D"),
  N_("Syloti Nagri"),
  N_("Common Indic Number Forms"),
  N_("Phags-pa"),
  N_("Saurashtra"),
  N_("Devanagari Extended"),
  N_("Kayah Li"),
  N_("Rejang"),
  N_("Hangul Jamo Extended-A"),
  N_("Javanese"),
  N_("Cham"),
  N_("Myanmar Extended-A"),
  N_("Tai Viet"),
  N_("Meetei Mayek"),
  N_("Hangul Syllables"),
  N_("Hangul Jamo Extended-B"),
  N_("High Surrogates"),
  N_("High Private Use Surrogates"),
  N_("Low Surrogates"),
  N_("Private Use Area"),
  N_("CJK Compatibility Ideographs"),
  N_("Alphabetic Presentation Forms"),
  N_("Arabic Presentation Forms-A"),
  N_("Variation Selectors"),
  N_("Vertical Forms"),
  N_("Combining Half Marks"),
  N_("CJK Compatibility Forms"),
  N_("Small Form Variants"),
  N_("Arabic Presentation Forms-B"),
  N_("Halfwidth and Fullwidth Forms"),
  N_("Specials"),
  N_("Linear B Syllabary"),
  N_("Linear B Ideograms"),
  N_("Aegean Numbers"),
  N_("Ancient Greek Numbers"),
  N_("Ancient Symbols"),
  N_("Phaistos Disc"),
  N_("Lycian"),
  N_("Carian"),
  N_("Old Italic"),
  N_("Gothic"),
  N_("Ugaritic"),
  N_("Old Persian"),
  N_("Deseret"),
  N_("Shavian"),
  N_("Osmanya"),
  N_("Cypriot Syllabary"),
  N_("Imperial Aramaic"),
  N_("Phoenician"),
  N_("Lydian"),
  N_("Kharoshthi"),
  N_("Old South Arabian"),
  N_("Avestan"),
  N_("Inscriptional Parthian"),
  N_("Inscriptional Pahlavi"),
  N_("Old Turkic"),
  N_("Rumi Numeral Symbols"),
  N_("Kaithi"),
  N_("Cuneiform"),
  N_("Cuneiform Numbers and Punctuation"),
  N_("Egyptian Hieroglyphs"),
  N_("Byzantine Musical Symbols"),
  N_("Musical Symbols"),
  N_("Ancient Greek Musical Notation"),
  N_("Tai Xuan Jing Symbols"),
  N_("Counting Rod Numerals"),
  N_("Mathematical Alphanumeric Symbols"),
  N_("Mahjong Tiles"),
  N_("Domino Tiles"),
  N_("Enclosed Alphanumeric Supplement"),
  N_("Enclosed Ideographic Supplement"),
  N_("CJK Unified Ideographs Extension B"),
  N_("CJK Unified Ideographs Extension C"),
  N_("CJK Compatibility Ideographs Supplement"),
  N_("Tags"),
  N_("Variation Selectors Supplement"),
  N_("Supplementary Private Use Area-A"),
  N_("Supplementary Private Use Area-B"),
#endif /* 0 */

static const char unicode_blocks_strings[] =
  "Basic Latin\0"
  "Latin-1 Supplement\0"
  "Latin Extended-A\0"
  "Latin Extended-B\0"
  "IPA Extensions\0"
  "Spacing Modifier Letters\0"
  "Combining Diacritical Marks\0"
  "Greek and Coptic\0"
  "Cyrillic\0"
  "Cyrillic Supplement\0"
  "Armenian\0"
  "Hebrew\0"
  "Arabic\0"
  "Syriac\0"
  "Arabic Supplement\0"
  "Thaana\0"
  "N'Ko\0"
  "Samaritan\0"
  "Devanagari\0"
  "Bengali\0"
  "Gurmukhi\0"
  "Gujarati\0"
  "Oriya\0"
  "Tamil\0"
  "Telugu\0"
  "Kannada\0"
  "Malayalam\0"
  "Sinhala\0"
  "Thai\0"
  "Lao\0"
  "Tibetan\0"
  "Myanmar\0"
  "Georgian\0"
  "Hangul Jamo\0"
  "Ethiopic\0"
  "Ethiopic Supplement\0"
  "Cherokee\0"
  "Unified Canadian Aboriginal Syllabics\0"
  "Ogham\0"
  "Runic\0"
  "Tagalog\0"
  "Hanunoo\0"
  "Buhid\0"
  "Tagbanwa\0"
  "Khmer\0"
  "Mongolian\0"
  "Unified Canadian Aboriginal Syllabics Extended\0"
  "Limbu\0"
  "Tai Le\0"
  "New Tai Lue\0"
  "Khmer Symbols\0"
  "Buginese\0"
  "Tai Tham\0"
  "Balinese\0"
  "Sundanese\0"
  "Lepcha\0"
  "Ol Chiki\0"
  "Vedic Extensions\0"
  "Phonetic Extensions\0"
  "Phonetic Extensions Supplement\0"
  "Combining Diacritical Marks Supplement\0"
  "Latin Extended Additional\0"
  "Greek Extended\0"
  "General Punctuation\0"
  "Superscripts and Subscripts\0"
  "Currency Symbols\0"
  "Combining Diacritical Marks for Symbols\0"
  "Letterlike Symbols\0"
  "Number Forms\0"
  "Arrows\0"
  "Mathematical Operators\0"
  "Miscellaneous Technical\0"
  "Control Pictures\0"
  "Optical Character Recognition\0"
  "Enclosed Alphanumerics\0"
  "Box Drawing\0"
  "Block Elements\0"
  "Geometric Shapes\0"
  "Miscellaneous Symbols\0"
  "Dingbats\0"
  "Miscellaneous Mathematical Symbols-A\0"
  "Supplemental Arrows-A\0"
  "Braille Patterns\0"
  "Supplemental Arrows-B\0"
  "Miscellaneous Mathematical Symbols-B\0"
  "Supplemental Mathematical Operators\0"
  "Miscellaneous Symbols and Arrows\0"
  "Glagolitic\0"
  "Latin Extended-C\0"
  "Coptic\0"
  "Georgian Supplement\0"
  "Tifinagh\0"
  "Ethiopic Extended\0"
  "Cyrillic Extended-A\0"
  "Supplemental Punctuation\0"
  "CJK Radicals Supplement\0"
  "Kangxi Radicals\0"
  "Ideographic Description Characters\0"
  "CJK Symbols and Punctuation\0"
  "Hiragana\0"
  "Katakana\0"
  "Bopomofo\0"
  "Hangul Compatibility Jamo\0"
  "Kanbun\0"
  "Bopomofo Extended\0"
  "CJK Strokes\0"
  "Katakana Phonetic Extensions\0"
  "Enclosed CJK Letters and Months\0"
  "CJK Compatibility\0"
  "CJK Unified Ideographs Extension A\0"
  "Yijing Hexagram Symbols\0"
  "CJK Unified Ideographs\0"
  "Yi Syllables\0"
  "Yi Radicals\0"
  "Lisu\0"
  "Vai\0"
  "Cyrillic Extended-B\0"
  "Bamum\0"
  "Modifier Tone Letters\0"
  "Latin Extended-D\0"
  "Syloti Nagri\0"
  "Common Indic Number Forms\0"
  "Phags-pa\0"
  "Saurashtra\0"
  "Devanagari Extended\0"
  "Kayah Li\0"
  "Rejang\0"
  "Hangul Jamo Extended-A\0"
  "Javanese\0"
  "Cham\0"
  "Myanmar Extended-A\0"
  "Tai Viet\0"
  "Meetei Mayek\0"
  "Hangul Syllables\0"
  "Hangul Jamo Extended-B\0"
  "High Surrogates\0"
  "High Private Use Surrogates\0"
  "Low Surrogates\0"
  "Private Use Area\0"
  "CJK Compatibility Ideographs\0"
  "Alphabetic Presentation Forms\0"
  "Arabic Presentation Forms-A\0"
  "Variation Selectors\0"
  "Vertical Forms\0"
  "Combining Half Marks\0"
  "CJK Compatibility Forms\0"
  "Small Form Variants\0"
  "Arabic Presentation Forms-B\0"
  "Halfwidth and Fullwidth Forms\0"
  "Specials\0"
  "Linear B Syllabary\0"
  "Linear B Ideograms\0"
  "Aegean Numbers\0"
  "Ancient Greek Numbers\0"
  "Ancient Symbols\0"
  "Phaistos Disc\0"
  "Lycian\0"
  "Carian\0"
  "Old Italic\0"
  "Gothic\0"
  "Ugaritic\0"
  "Old Persian\0"
  "Deseret\0"
  "Shavian\0"
  "Osmanya\0"
  "Cypriot Syllabary\0"
  "Imperial Aramaic\0"
  "Phoenician\0"
  "Lydian\0"
  "Kharoshthi\0"
  "Old South Arabian\0"
  "Avestan\0"
  "Inscriptional Parthian\0"
  "Inscriptional Pahlavi\0"
  "Old Turkic\0"
  "Rumi Numeral Symbols\0"
  "Kaithi\0"
  "Cuneiform\0"
  "Cuneiform Numbers and Punctuation\0"
  "Egyptian Hieroglyphs\0"
  "Byzantine Musical Symbols\0"
  "Musical Symbols\0"
  "Ancient Greek Musical Notation\0"
  "Tai Xuan Jing Symbols\0"
  "Counting Rod Numerals\0"
  "Mathematical Alphanumeric Symbols\0"
  "Mahjong Tiles\0"
  "Domino Tiles\0"
  "Enclosed Alphanumeric Supplement\0"
  "Enclosed Ideographic Supplement\0"
  "CJK Unified Ideographs Extension B\0"
  "CJK Unified Ideographs Extension C\0"
  "CJK Compatibility Ideographs Supplement\0"
  "Tags\0"
  "Variation Selectors Supplement\0"
  "Supplementary Private Use Area-A\0"
  "Supplementary Private Use Area-B\0"
  ;

typedef struct _UnicodeBlock UnicodeBlock;

static const struct _UnicodeBlock
{
  gunichar start;
  gunichar end;
  guint16 block_name_index;
}
unicode_blocks[] =
{
  { 0x0000, 0x007F, 0 },
  { 0x0080, 0x00FF, 12 },
  { 0x0100, 0x017F, 31 },
  { 0x0180, 0x024F, 48 },
  { 0x0250, 0x02AF, 65 },
  { 0x02B0, 0x02FF, 80 },
  { 0x0300, 0x036F, 105 },
  { 0x0370, 0x03FF, 133 },
  { 0x0400, 0x04FF, 150 },
  { 0x0500, 0x052F, 159 },
  { 0x0530, 0x058F, 179 },
  { 0x0590, 0x05FF, 188 },
  { 0x0600, 0x06FF, 195 },
  { 0x0700, 0x074F, 202 },
  { 0x0750, 0x077F, 209 },
  { 0x0780, 0x07BF, 227 },
  { 0x07C0, 0x07FF, 234 },
  { 0x0800, 0x083F, 239 },
  { 0x0900, 0x097F, 249 },
  { 0x0980, 0x09FF, 260 },
  { 0x0A00, 0x0A7F, 268 },
  { 0x0A80, 0x0AFF, 277 },
  { 0x0B00, 0x0B7F, 286 },
  { 0x0B80, 0x0BFF, 292 },
  { 0x0C00, 0x0C7F, 298 },
  { 0x0C80, 0x0CFF, 305 },
  { 0x0D00, 0x0D7F, 313 },
  { 0x0D80, 0x0DFF, 323 },
  { 0x0E00, 0x0E7F, 331 },
  { 0x0E80, 0x0EFF, 336 },
  { 0x0F00, 0x0FFF, 340 },
  { 0x1000, 0x109F, 348 },
  { 0x10A0, 0x10FF, 356 },
  { 0x1100, 0x11FF, 365 },
  { 0x1200, 0x137F, 377 },
  { 0x1380, 0x139F, 386 },
  { 0x13A0, 0x13FF, 406 },
  { 0x1400, 0x167F, 415 },
  { 0x1680, 0x169F, 453 },
  { 0x16A0, 0x16FF, 459 },
  { 0x1700, 0x171F, 465 },
  { 0x1720, 0x173F, 473 },
  { 0x1740, 0x175F, 481 },
  { 0x1760, 0x177F, 487 },
  { 0x1780, 0x17FF, 496 },
  { 0x1800, 0x18AF, 502 },
  { 0x18B0, 0x18FF, 512 },
  { 0x1900, 0x194F, 559 },
  { 0x1950, 0x197F, 565 },
  { 0x1980, 0x19DF, 572 },
  { 0x19E0, 0x19FF, 584 },
  { 0x1A00, 0x1A1F, 598 },
  { 0x1A20, 0x1AAF, 607 },
  { 0x1B00, 0x1B7F, 616 },
  { 0x1B80, 0x1BBF, 625 },
  { 0x1C00, 0x1C4F, 635 },
  { 0x1C50, 0x1C7F, 642 },
  { 0x1CD0, 0x1CFF, 651 },
  { 0x1D00, 0x1D7F, 668 },
  { 0x1D80, 0x1DBF, 688 },
  { 0x1DC0, 0x1DFF, 719 },
  { 0x1E00, 0x1EFF, 758 },
  { 0x1F00, 0x1FFF, 784 },
  { 0x2000, 0x206F, 799 },
  { 0x2070, 0x209F, 819 },
  { 0x20A0, 0x20CF, 847 },
  { 0x20D0, 0x20FF, 864 },
  { 0x2100, 0x214F, 904 },
  { 0x2150, 0x218F, 923 },
  { 0x2190, 0x21FF, 936 },
  { 0x2200, 0x22FF, 943 },
  { 0x2300, 0x23FF, 966 },
  { 0x2400, 0x243F, 990 },
  { 0x2440, 0x245F, 1007 },
  { 0x2460, 0x24FF, 1037 },
  { 0x2500, 0x257F, 1060 },
  { 0x2580, 0x259F, 1072 },
  { 0x25A0, 0x25FF, 1087 },
  { 0x2600, 0x26FF, 1104 },
  { 0x2700, 0x27BF, 1126 },
  { 0x27C0, 0x27EF, 1135 },
  { 0x27F0, 0x27FF, 1172 },
  { 0x2800, 0x28FF, 1194 },
  { 0x2900, 0x297F, 1211 },
  { 0x2980, 0x29FF, 1233 },
  { 0x2A00, 0x2AFF, 1270 },
  { 0x2B00, 0x2BFF, 1306 },
  { 0x2C00, 0x2C5F, 1339 },
  { 0x2C60, 0x2C7F, 1350 },
  { 0x2C80, 0x2CFF, 1367 },
  { 0x2D00, 0x2D2F, 1374 },
  { 0x2D30, 0x2D7F, 1394 },
  { 0x2D80, 0x2DDF, 1403 },
  { 0x2DE0, 0x2DFF, 1421 },
  { 0x2E00, 0x2E7F, 1441 },
  { 0x2E80, 0x2EFF, 1466 },
  { 0x2F00, 0x2FDF, 1490 },
  { 0x2FF0, 0x2FFF, 1506 },
  { 0x3000, 0x303F, 1541 },
  { 0x3040, 0x309F, 1569 },
  { 0x30A0, 0x30FF, 1578 },
  { 0x3100, 0x312F, 1587 },
  { 0x3130, 0x318F, 1596 },
  { 0x3190, 0x319F, 1622 },
  { 0x31A0, 0x31BF, 1629 },
  { 0x31C0, 0x31EF, 1647 },
  { 0x31F0, 0x31FF, 1659 },
  { 0x3200, 0x32FF, 1688 },
  { 0x3300, 0x33FF, 1720 },
  { 0x3400, 0x4DBF, 1738 },
  { 0x4DC0, 0x4DFF, 1773 },
  { 0x4E00, 0x9FFF, 1797 },
  { 0xA000, 0xA48F, 1820 },
  { 0xA490, 0xA4CF, 1833 },
  { 0xA4D0, 0xA4FF, 1845 },
  { 0xA500, 0xA63F, 1850 },
  { 0xA640, 0xA69F, 1854 },
  { 0xA6A0, 0xA6FF, 1874 },
  { 0xA700, 0xA71F, 1880 },
  { 0xA720, 0xA7FF, 1902 },
  { 0xA800, 0xA82F, 1919 },
  { 0xA830, 0xA83F, 1932 },
  { 0xA840, 0xA87F, 1958 },
  { 0xA880, 0xA8DF, 1967 },
  { 0xA8E0, 0xA8FF, 1978 },
  { 0xA900, 0xA92F, 1998 },
  { 0xA930, 0xA95F, 2007 },
  { 0xA960, 0xA97F, 2014 },
  { 0xA980, 0xA9DF, 2037 },
  { 0xAA00, 0xAA5F, 2046 },
  { 0xAA60, 0xAA7F, 2051 },
  { 0xAA80, 0xAADF, 2070 },
  { 0xABC0, 0xABFF, 2079 },
  { 0xAC00, 0xD7AF, 2092 },
  { 0xD7B0, 0xD7FF, 2109 },
  { 0xD800, 0xDB7F, 2132 },
  { 0xDB80, 0xDBFF, 2148 },
  { 0xDC00, 0xDFFF, 2176 },
  { 0xE000, 0xF8FF, 2191 },
  { 0xF900, 0xFAFF, 2208 },
  { 0xFB00, 0xFB4F, 2237 },
  { 0xFB50, 0xFDFF, 2267 },
  { 0xFE00, 0xFE0F, 2295 },
  { 0xFE10, 0xFE1F, 2315 },
  { 0xFE20, 0xFE2F, 2330 },
  { 0xFE30, 0xFE4F, 2351 },
  { 0xFE50, 0xFE6F, 2375 },
  { 0xFE70, 0xFEFF, 2395 },
  { 0xFF00, 0xFFEF, 2423 },
  { 0xFFF0, 0xFFFF, 2453 },
  { 0x10000, 0x1007F, 2462 },
  { 0x10080, 0x100FF, 2481 },
  { 0x10100, 0x1013F, 2500 },
  { 0x10140, 0x1018F, 2515 },
  { 0x10190, 0x101CF, 2537 },
  { 0x101D0, 0x101FF, 2553 },
  { 0x10280, 0x1029F, 2567 },
  { 0x102A0, 0x102DF, 2574 },
  { 0x10300, 0x1032F, 2581 },
  { 0x10330, 0x1034F, 2592 },
  { 0x10380, 0x1039F, 2599 },
  { 0x103A0, 0x103DF, 2608 },
  { 0x10400, 0x1044F, 2620 },
  { 0x10450, 0x1047F, 2628 },
  { 0x10480, 0x104AF, 2636 },
  { 0x10800, 0x1083F, 2644 },
  { 0x10840, 0x1085F, 2662 },
  { 0x10900, 0x1091F, 2679 },
  { 0x10920, 0x1093F, 2690 },
  { 0x10A00, 0x10A5F, 2697 },
  { 0x10A60, 0x10A7F, 2708 },
  { 0x10B00, 0x10B3F, 2726 },
  { 0x10B40, 0x10B5F, 2734 },
  { 0x10B60, 0x10B7F, 2757 },
  { 0x10C00, 0x10C4F, 2779 },
  { 0x10E60, 0x10E7F, 2790 },
  { 0x11080, 0x110CF, 2811 },
  { 0x12000, 0x123FF, 2818 },
  { 0x12400, 0x1247F, 2828 },
  { 0x13000, 0x1342F, 2862 },
  { 0x1D000, 0x1D0FF, 2883 },
  { 0x1D100, 0x1D1FF, 2909 },
  { 0x1D200, 0x1D24F, 2925 },
  { 0x1D300, 0x1D35F, 2956 },
  { 0x1D360, 0x1D37F, 2978 },
  { 0x1D400, 0x1D7FF, 3000 },
  { 0x1F000, 0x1F02F, 3034 },
  { 0x1F030, 0x1F09F, 3048 },
  { 0x1F100, 0x1F1FF, 3061 },
  { 0x1F200, 0x1F2FF, 3094 },
  { 0x20000, 0x2A6DF, 3126 },
  { 0x2A700, 0x2B73F, 3161 },
  { 0x2F800, 0x2FA1F, 3196 },
  { 0xE0000, 0xE007F, 3236 },
  { 0xE0100, 0xE01EF, 3241 },
  { 0xF0000, 0xFFFFF, 3272 },
  { 0x100000, 0x10FFFF, 3305 },
};

#endif  /* #ifndef UNICODE_BLOCKS_H */
