#!/bin/bash

# fill it
pkgname=mate-vfs
pkgver=2011.9.26
pkgrel=1
pkgdesc="The MATE Virtual File System"
makedepends=('mate-common' 'libbz2-dev' 'libgcrypt11-dev' 'libgnutls-dev' 'libgamin-dev' 'libtool' 'gtk-doc-utils')

# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf download
	# entramos a la carpeta
	cd ${pkgname}

	#Fix build with new gnutls
	libtoolize --force
	gtkdocize
	aclocal
	autoconf
	automake
	./configure --prefix=/usr --sysconfdir=/etc \
		--localstatedir=/var --disable-static \
		--libexecdir=/usr/lib/${pkgname} \
		--enable-openssl
		#--enable-samba --disable-hal \
		#--enable-avahi --disable-howl \
		#--disable-openssl --enable-gnutls
	make

	make MATECONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=1 DESTDIR="${pkgdir}" install

	install -d -m755 "${pkgdir}/usr/share/mateconf/schemas"
	mateconf-merge-schema "${pkgdir}/usr/share/mateconf/schemas/${pkgname}.schemas" --domain ${pkgname} ${pkgdir}/etc/mateconf/schemas/*.schemas
	rm -f ${pkgdir}/etc/mateconf/schemas/*.schemas
}

# esto incluye la parte que se repite en la mayoria de los builds
. /usr/share/mate-doc-utils/mate-debian.sh
