#!/bin/bash

# fill it
pkgname=mate-vfs
pkgver=2011.10.29
pkgrel=1
pkgdesc="The MATE Virtual File System"
depends=('gvfs' 'mate-conf' 'mate-mime-data')
makedepends=('mate-common' 'libbz2-dev' 'libgcrypt11-dev' 'libgnutls-dev' 'libgamin-dev' 'libtool' 'gtk-doc-tools')

# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf download
	# entramos a la carpeta
	cd ${pkgname}

	./configure --prefix=/usr --sysconfdir=/etc \
		--localstatedir=/var --disable-static \
		--libexecdir=/usr/lib/${pkgname} \
		--disable-samba --disable-hal \
		--disable-avahi --disable-howl \
		--disable-openssl || return 1
	make || return 1

	make MATECONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=1 DESTDIR="${pkgdir}" install || return 1

	install -d -m755 "${pkgdir}/usr/share/mateconf/schemas"
	mateconf-merge-schema "${pkgdir}/usr/share/mateconf/schemas/${pkgname}.schemas" --domain ${pkgname} ${pkgdir}/etc/mateconf/schemas/*.schemas
	rm -f ${pkgdir}/etc/mateconf/schemas/*.schemas
}

# esto incluye la parte que se repite en la mayoria de los builds
. /usr/share/mate-doc-utils/mate-debian.sh
