.\" mate-dictionary.1 - a online dictionary client
.\" Copyright 2005  Emmanuele Bassi
.\" Copyright 2001  Jochen Voss
.TH mate-dictionary 1 "Jan 2 2005" "mate-utils 2.13.4"
.SH NAME
mate-dictionary \- Look up words on dictionaries
.SH SYNOPSIS
.nf
.BI mate-dictionary
.br
.BI mate-dictionary " [options]"
.fi
.sp
or select
.B Dictionary
from the
.B Accessories
submenu of the Applications menu.
.SH DESCRIPTION
.B MATE Dictionary
provides dictionary definitions of words, using a dictionary source.

For full documentation see the
.B MATE Dictionary
online help.

.SH OPTIONS
.TP
.BI \-\-look\-up " word"
Looks up the specified word using the pre-defined dictionary source.
.TP
.BI \-s " source\fR or " \-\-source " source"
Uses the specified source for looking up words.  This does not affect the
global settings.
.TP
.BR \-l " or " \-\-list\-sources
Lists all the sources available.
.TP
.BR \-n " or " \-\-no\-window
Using this switch with the \-\-look\-up will print the definitions found
on the console without launching the GUI.
.TP
.B \-\-help
Display help information.
.SH CONFIGURATION
All the configuration is handled using MateConf.
.SH AUTHOR
.B MATE Dictionary
was originally written by Spiros Papadimitriou (<spapadim+@cs.cmu.edu>), Mike
Hughes (<mfh@psilord.com>) and Bradford Hovinen (<hovinen@udel.edu>).

Emmanuele Bassi (<ebassi@gmail.com>) rewrote it from scratch.

This manual page was originally written by Jochen Voss
<voss@mathematik.uni-kl.de>.

.SH SEE ALSO
.BR dict (1),
.BR dictd (8),
.BR http://www.dict.org/ ,
.B RFC 2229
