.\"
.\" mate-session-properties manual page.
.\" (C) 2009-2010 Vincent Untz (vuntz@gnome.org)
.\"
.TH MATE-SESSION-PROPERTIES 1 "MATE"
.SH NAME
mate-session-properties \- Configure applications to start on login
.SH SYNOPSIS
.B mate-session-properties
.SH DESCRIPTION
.PP
The \fImate-session-properties\fP program enables the users to
configure what applications should be started on login, in addition to
the default startup applications configured on the system.
.PP
It also proposes an interface to save a snapshot of the currently
running applications so that they can automatically be restored to
their current state on your next MATE session.
.SH BUGS
If you find bugs in the \fImate-session-properties\fP program, please report
these on https://bugzilla.gnome.org.
.SH SEE ALSO
.BR mate-session(1)
.BR mate-session-save(1)
