.\"
.\" mate-session-save manual page.
.\" (C) 2000 Miguel de Icaza (miguel@helixcode.com)
.\" (C) 2009-2010 Vincent Untz (vuntz@gnome.org)
.\"
.TH MATE-SESSION-SAVE 1 "MATE"
.SH NAME
mate-session-save \- End or save the current MATE session
.SH SYNOPSIS
.B mate-session-save [\-\-logout] [\-\-force\-logout] [\-\-logout\-dialog] [\-\-shutdown\-dialog] [\-\-gui] [\-\-kill [\-\-silent]]
.SH DESCRIPTION
The \fImate-session-save\fP program can be used from a MATE session to
save a snapshot of the currently running applications. This session will
be later restored at your next MATE session.
.PP
The \fB\-\-gui\fP option will report errors in dialog boxes instead of
printing to stderr.
.PP
If called with the \fB\-\-logout\fP option, the current MATE session will be
ended, unless logging out has been inhibited by an application. The
\fB\-\-force\-logout\fP option can be used to end the session regardless of
the inhibition state.
.PP
When the \fB\-\-logout\-dialog\fP option is given, the standard dialog
displaying logout options is displayed. When \fB\-\-shutdown\-dialog\fP
option is given, the standard dialog displaying shutdown options is
displayed.
.PP
The \fB\-\-kill\fP and \fB\-\-silent\fP options are deprecated. The
\fB\-\-kill\fP option is equivalent to the \fB\-\-logout\-dialog\fP
option. If \fB\-\-silent\fP is used with \fB\-\-kill\fR, then it will
behave as if \fB\-\-logout\fP was used.
.PP
The session is not saved when \fImate-session-save\fP is called with any of
the options ending the session.
.SH BUGS
If you find bugs in the \fImate-session-save\fP program, please report
these on https://bugzilla.gnome.org.
.SH SEE ALSO
.BR mate-session(1)
