.\"
.\" mate-wm manual page.
.\" (C) 2000 Miguel de Icaza (miguel@helixcode.com)
.\" (C) 2009-2010 Vincent Untz (vuntz@gnome.org)
.\"
.TH MATE-WM 1 "MATE"
.SH NAME
mate-wm \- Start the window manager configured by the user
.SH SYNOPSIS
.PP
.B mate-wm [--default-wm=WINDOWMANAGER] [--sm-client-id=ID]
.SH DESCRIPTION
The \fImate-wm\fP program starts the window manager configured by the
user. If the user has not chosen a window manager it will launch a
MATE compliant window manager.
.PP
The user can define his preferred window manager with the
\fB/desktop/mate/session/required_components/windowmanager\fP MateConf
key. The value of this key should be the name of the desktop file of the
desired window manager, without its \fB.desktop\fP extension. If this
key is set to \fImate-wm\fP, then \fImate-wm\fP will simply look for
an appropriate window manager. The user can also override the selection
of a window manager by setting the \fBWINDOW_MANAGER\fP environment
variable.
.PP
If the \fB--default-wm\fP option is used, \fImate-wm\fP will use
\fIWINDOWMANAGER\fP as window manager if the \fBWINDOW_MANAGER\fP
environment variable is not set and if the
\fB/desktop/mate/session/required_components/windowmanager\fP MateConf
key does not define a specific window manager, or if the configured
window manager cannot be found.
.PP
The \fB--sm-client-id\fP option is translated to an appropriate option
depending on which window manager will be started.
.SH OPTIONS
The following options are supported:
.TP
.I --default-wm=WINDOWMANAGER
Define the default window manager to start if no window manager is
configured, or if the configured window manager cannot be found.
.TP
.I --sm-client-id=ID
Specify the session management \fIID\fP when connecting to the session manager.
.SH ENVIRONMENT
\fImate-wm\fP uses the value of the \fBWINDOW_MANAGER\fP environment
variable to let the user override the configured window manager.
.SH BUGS
If you find bugs in the \fImate-wm\fP program, please report
these on https://bugzilla.gnome.org.
.SH SEE ALSO
.BR mate-session(1)
