#!/bin/bash

# fill it
pkgname=mate-conf-editor
pkgver=0.0.0-1
pkgdesc="A configuration database system editor"
#depends="mate-corba, libxml2, polkit, libldap, dbus-glib, gtk2, mate-conf"

# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf ${pkgname}.tar.gz
	# entramos a la carpeta
	cd ${pkgname}
	
	./configure --prefix=/usr --sysconfdir=/etc \
		--libexecdir=/usr/lib/MateConf \
		--localstatedir=/var || return 1

	make || return 1
	make MATECONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=1 DESTDIR="${pkgdir}" install || return 1

	install -m755 -d ${pkgdir}/usr/share/mateconf/schemas

	mateconf-merge-schema ${pkgdir}/usr/share/mateconf/schemas/${pkgname}.schemas --domain ${pkgname} ${pkgdir}/etc/mateconf/schemas/*.schemas || return 1
	rm -f ${pkgdir}/etc/mateconf/schemas/*.schemas
}

# esto incluye la parte que se repite en la mayoria de los builds
. ../common
