#!/bin/sh

pkgname=mate-control-center

/usr/sbin/mateconfpkg --install ${pkgname}
update-desktop-database -q
gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
update-mime-database /usr/share/mime

exit 0
