#!/bin/sh

pkgname=mate-control-center

if [ -f /usr/sbin/mateconfpkg ]; then
	/usr/sbin/mateconfpkg --install ${pkgname}
fi

update-desktop-database -q
gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
update-mime-database /usr/share/mime

exit 0
