#!/bin/bash

# fill it
pkgname=libmatenotify
pkgver=0.0.0-1
pkgdesc="Desktop notification library"
#depends="gdk-pixbuf2"
# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf ${pkgname}.tar.gz
	# entramos a la carpeta
	cd ${pkgname}
	
	./configure --prefix=/usr --disable-static
	make
	make DESTDIR="${pkgdir}" install
}

# esto incluye la parte que se repite en la mayoria de los builds
. ../common
