.\" mate-search-tool.1 - MATE Search Tool
.\" Copyright 2001  Jochen Voss
.TH mate-search-tool 1 "March 16 2009" "mate-utils 2.27.1"
.SH NAME
mate-search-tool \- the MATE Search Tool
.SH SYNOPSIS
.B mate-search-tool
.RI [ options ]
.sp
or select
.B Search for Files...
from a
.B Main Menu
or from the
.B Places
menu in a
.B Menu Bar
.SH DESCRIPTION
.B MATE Search Tool
is a utility for finding files on your system. To perform a
basic search, you can type a filename or a partial filename,
with or without wildcards. To refine your search, you can
apply additional search options.

.B MATE Search Tool
uses the find, grep, and locate UNIX commands. The case
sensitivity of the search depends on your operating
system. For example, on Linux, the find, grep, and locate
commands support the -i option, so all searches are
case-insensitive.

For full documentation see the
.B MATE Search Tool
online help.

.SH OPTIONS
.TP
.BR \-\-help
Show help message
.TP
.BI "\-\-named=" STRING
Set the text of "Name contains" search option
.TP
.BI "\-\-path=" PATH
Set the text of "Look in folder" search option
.TP
.BI "\-\-sortby=" VALUE
Sort files by one of the following: name, folder, size, type, or date
.TP
.BR \-\-descending
Set sort order to descending, the default is ascending
.TP
.BR \-\-start
Automatically start a search
.TP
.BI "\-\-contains=" STRING
Select and set the "Contains the text" search option
.TP
.BI "\-\-mtimeless=" DAYS
Select and set the "Date modified less than" search option
.TP
.BI "\-\-mtimemore=" DAYS
Select and set the "Date modified more than" search option
.TP
.BI "\-\-sizemore=" KILOBYTES
Select and set the "Size at least" search option
.TP
.BI "\-\-sizeless=" KILOBYTES
Select and set the "Size at most" search option
.TP
.BR \-\-empty
Select the "File is empty" search option
.TP
.BI "\-\-user=" USER
Select and set the "Owned by user" search option
.TP
.BI "\-\-group=" GROUP
Select and set the "Owned by group" search option
.TP
.BR \-\-nouser
Select the "Owner is unrecognized" search option
.TP
.BI "\-\-notnamed=" STRING
Select and set the "Name does not contain" search option
.TP
.BI "\-\-regex=" PATTERN
Select and set the "Name matches regular expression" search option
.TP
.BR \-\-hidden
Select the "Show hidden and backup files" search option
.TP
.BR \-\-follow
Select the "Follow symbolic links" search option
.TP
.BR \-\-mounts
Select the "Exclude other filesystems" search option
.SH AUTHOR
.B MATE Search Tool
was originally written by George Lebl (<jirka@5z.com>).
Version 2 was written by Dennis M. Cranston
(<dennis_cranston@yahoo.com>).

This manual page was originally written by Jochen Voss
<voss@mathematik.uni-kl.de>.  Version 2 was written by
Dennis M. Cranston (<dennis_cranston@yahoo.com>).

.SH SEE ALSO
.BR find (1),
.BR locate (1),
.BR grep (1)
