.TH BLUETOOTH-WIZARD 1 "Oct 4, 2006" "bluez-mate" "Linux User's Manual"
.SH NAME
bluetooth-wizard - GTK wizard for setting up devices with the Linux Bluetooth stack
.SH SYNOPSIS
.B bluetooth-wizard
.SH DESCRIPTION
.I bluetooth-wizard
will display a wizard for setting up Bluetooth devices.
.I bluetooth-wizard
is part of bluez-mate, see also http://www.bluez.org
.SH OPTIONS
.I bluetooth-wizard
takes no options
.SH AUTHOR
Marcel Holtmann <marcel@holtmann.org>
.SH LICENSE
bluetooth-wizard is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the Free
Software Foundation; either version 2 of the License, or (at your option)
any later version.

This program is distributed in the hope that it will be useful but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
