#!/bin/bash

# fill it
pkgname=libmatekbd
pkgver=0.0.0-1
pkgdesc="MATE keyboard library"
#depends="libxklavier, mate-conf"
# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf ${pkgname}.tar.gz
	# entramos a la carpeta
	cd ${pkgname}
	
	./configure --prefix=/usr --sysconfdir=/etc
	automake
	make
	make MATECONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=1 DESTDIR="${pkgdir}" install
	
	install -m755 -d "${pkgdir}/usr/share/mateconf/schemas"
	mateconf-merge-schema "${pkgdir}/usr/share/mateconf/schemas/${pkgname}.schemas" --domain ${pkgname} ${pkgdir}/etc/mateconf/schemas/*.schemas || return 1
	rm -f ${pkgdir}/etc/mateconf/schemas/*.schemas
}

# esto incluye la parte que se repite en la mayoria de los builds
. ../common
