#!/bin/bash

# fill it
pkgname=mate-themes
pkgver=0.0.0-1
pkgdesc="Default themes for the MATE desktop"
#depends="gtk2, gtk-engines"
# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf ${pkgname}.tar.gz
	# entramos a la carpeta
	cd ${pkgname}
	
	./configure --prefix=/usr || return 1
	make || return 1
    make DESTDIR="$pkgdir" install || return 1
}

# esto incluye la parte que se repite en la mayoria de los builds
. ../common
