/*
 * This file was generated by matecorba-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define MATECORBA2_STUBS_API
#include "MateComponent_Sample_Echo.h"

void MateComponent_Sample_Echo_echo(MateComponent_Sample_Echo _obj, const CORBA_char * message, CORBA_Environment *ev){
gpointer _args[1];
_args[0] = (gpointer)&message;
MateCORBA_c_stub_invoke (_obj, &MateComponent_Sample_Echo__iinterface.methods, 0, NULL, _args, NULL, ev, MateComponent_Sample_Echo__classid, G_STRUCT_OFFSET (POA_MateComponent_Sample_Echo__epv, echo),
(MateCORBASmallSkeleton) _MATECORBA_skel_small_MateComponent_Sample_Echo_echo);

}
