/*
 * This file was generated by matecorba-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define MATECORBA2_STUBS_API
#define MATECORBA_IDL_C_COMMON
#define MateComponent_Sample_Echo_COMMON
#include "MateComponent_Sample_Echo.h"

static const CORBA_unsigned_long MateCORBA_zero_int = 0;

#ifndef MATECORBA_IDL_C_IMODULE_MateComponent_Sample_Echo
void _MATECORBA_skel_small_MateComponent_Sample_Echo_echo(POA_MateComponent_Sample_Echo             *_o_servant, gpointer            _o_retval,gpointer           *_o_args,CORBA_Context       _o_ctx,CORBA_Environment  *_o_ev,
void (*_impl_echo)(PortableServer_Servant _servant, const CORBA_char * message, CORBA_Environment *ev)) {
_impl_echo (_o_servant, *(const CORBA_char * *)_o_args[0], _o_ev);
}

#endif
#if ( (TC_IMPL_TC_MateComponent_Sample_Echo_0 == 'M') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_1 == 'a') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_2 == 't') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_3 == 'e') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_4 == 'C') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_5 == 'o') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_6 == 'm') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_7 == 'p') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_8 == 'o') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_9 == 'n') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_10 == 'e') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_11 == 'n') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_12 == 't') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_13 == '_') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_14 == 'S') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_15 == 'a') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_16 == 'm') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_17 == 'p') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_18 == 'l') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_19 == 'e') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_20 == '_') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_21 == 'E') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_22 == 'c') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_23 == 'h') \
&& (TC_IMPL_TC_MateComponent_Sample_Echo_24 == 'o') \
) && !defined(TC_DEF_TC_MateComponent_Sample_Echo)
#define TC_DEF_TC_MateComponent_Sample_Echo 1
#ifdef MATECORBA_IDL_C_IMODULE_MateComponent_Sample_Echo
static
#endif
MATECORBA2_MAYBE_CONST struct CORBA_TypeCode_struct TC_MateComponent_Sample_Echo_struct = {
{&MateCORBA_TypeCode_epv, MATECORBA_REFCOUNT_STATIC},
CORBA_tk_objref,
0,
0,
MATECORBA_ALIGNOF_CORBA_POINTER,
0,
0
,
NULL,
CORBA_OBJECT_NIL,
(char *)"Echo",
(char *)"IDL:MateComponent/Sample/Echo:1.0",
NULL,
NULL,
-1,
0,
0, 0
};
#endif

#ifndef MATECORBA_IDL_C_IMODULE_MateComponent_Sample_Echo
CORBA_unsigned_long MateComponent_Sample_Echo__classid = 0;
#endif

/* Interface type data */

static MateCORBA_IArg MateComponent_Sample_Echo_echo__arginfo [] = {
	{ TC_CORBA_string,  MateCORBA_I_ARG_IN , (char *)"message" }
};

#ifdef MATECORBA_IDL_C_IMODULE_MateComponent_Sample_Echo
static
#endif
MateCORBA_IMethod MateComponent_Sample_Echo__imethods [] = {
	{
		{ 1, 1, MateComponent_Sample_Echo_echo__arginfo, FALSE },
		{ 0, 0, NULL, FALSE },
		{ 0, 0, NULL, FALSE },
TC_void, (char *)"echo", 4,
		0
}
};

static CORBA_string MateComponent_Sample_Echo__base_itypes[] = {
(char *)"IDL:MateComponent/Unknown:1.0",
(char *)"IDL:omg.org/CORBA/Object:1.0"
};
#ifdef MATECORBA_IDL_C_IMODULE_MateComponent_Sample_Echo
static
#endif
MateCORBA_IInterface MateComponent_Sample_Echo__iinterface = {
TC_MateComponent_Sample_Echo,{1, 1, MateComponent_Sample_Echo__imethods, FALSE},
{2, 2, MateComponent_Sample_Echo__base_itypes, FALSE}
};

