/*
 * This file was generated by matecorba-idl-2 - DO NOT EDIT!
 */

#include <string.h>
#define MATECORBA2_STUBS_API
#include "MateComponent_Sample_Echo.h"

static MateCORBASmallSkeleton get_skel_small_MateComponent_Sample_Echo(POA_MateComponent_Sample_Echo *servant,
const char *opname,gpointer *m_data, gpointer *impl)
{
switch(opname[0]) {
case 'e':
if(strcmp((opname + 1), "cho")) break;
*impl = (gpointer)servant->vepv->MateComponent_Sample_Echo_epv->echo;
{MateCORBA_IInterface *volatile _t_=&MateComponent_Sample_Echo__iinterface;*m_data = (gpointer)&_t_->methods._buffer [0];}
return (MateCORBASmallSkeleton)_MATECORBA_skel_small_MateComponent_Sample_Echo_echo;
break;
case 'q':
if(strcmp((opname + 1), "ueryInterface")) break;
*impl = (gpointer)servant->vepv->MateComponent_Unknown_epv->queryInterface;
{MateCORBA_IInterface *volatile _t_=&MateComponent_Unknown__iinterface;*m_data = (gpointer)&_t_->methods._buffer [2];}
return (MateCORBASmallSkeleton)_MATECORBA_skel_small_MateComponent_Unknown_queryInterface;
break;
case 'r':
if(strcmp((opname + 1), "ef")) break;
*impl = (gpointer)servant->vepv->MateComponent_Unknown_epv->ref;
{MateCORBA_IInterface *volatile _t_=&MateComponent_Unknown__iinterface;*m_data = (gpointer)&_t_->methods._buffer [0];}
return (MateCORBASmallSkeleton)_MATECORBA_skel_small_MateComponent_Unknown_ref;
break;
case 'u':
if(strcmp((opname + 1), "nref")) break;
*impl = (gpointer)servant->vepv->MateComponent_Unknown_epv->unref;
{MateCORBA_IInterface *volatile _t_=&MateComponent_Unknown__iinterface;*m_data = (gpointer)&_t_->methods._buffer [1];}
return (MateCORBASmallSkeleton)_MATECORBA_skel_small_MateComponent_Unknown_unref;
break;
default: break; 
}
return NULL;
}

void POA_MateComponent_Sample_Echo__init(PortableServer_Servant servant,
CORBA_Environment *env)
{
  static PortableServer_ClassInfo class_info = {NULL, (MateCORBA_small_impl_finder)&get_skel_small_MateComponent_Sample_Echo, "IDL:MateComponent/Sample/Echo:1.0", &MateComponent_Sample_Echo__classid, NULL, &MateComponent_Sample_Echo__iinterface};
  PortableServer_ServantBase__init (       ((PortableServer_ServantBase *)servant), env);
  POA_MateComponent_Unknown__init(servant, env);
   MateCORBA_skel_class_register (&class_info,
   (PortableServer_ServantBase *)servant, POA_MateComponent_Sample_Echo__fini,
   MATECORBA_VEPV_OFFSET (POA_MateComponent_Sample_Echo__vepv, MateComponent_Sample_Echo_epv),
(CORBA_unsigned_long) MateComponent_Unknown__classid,
MATECORBA_VEPV_OFFSET (POA_MateComponent_Sample_Echo__vepv, MateComponent_Unknown_epv),
   (CORBA_unsigned_long) 0);}

void POA_MateComponent_Sample_Echo__fini(PortableServer_Servant servant,
CORBA_Environment *env)
{
  POA_MateComponent_Unknown__fini(servant, env);
  PortableServer_ServantBase__fini(servant, env);
}

