.TH MATECONF\-EDITOR 1 "12 June 2003"
.SH NAME
mateconf\-editor \- an editor for the MateConf configuration system
.SH SYNOPSIS
.B mateconf\-editor
.SH DESCRIPTION
\fBMateConf\-Editor\fP is a tool used for editing the MateConf configuration
database.
It might be useful when the proper configuration utility for some
software provides no way of changing some option.
.SH USAGE
The main window consists of a tree showing the MateConf configuration
database hierarchy, a list of the keys available, and documentation
for the selected key.

Key values can be changed by either changing them directly in the
list, or right clicking on them and selecting \fIEdit key\fP.
Changes take immediate effect in running programs.
New keys can be added by right clicking in the list and selecting
\fINew key\fP.

Bookmarks may be set for quick lookup of a key later.
.SH NOTES
This tool allows you to directly edit your configuration database.
This is not the recommended way of setting desktop preferences.
Use this tool at your own risk.
.SH AUTHOR
Anders Carlsson <andersca@gnu.org>.
.br
This manual page was written by G\[:o]ran Weinholt for the Debian project,
but may be used by others.
.SH REPORTING BUGS
Please report bugs at http://bugzilla.mate.org/.
.SH SEE ALSO
.BR mateconfd\-2 (1),
.BR mateconftool\-2 (1).

.I http://www.mate.org/projects/mateconf/
