#!/bin/bash

# fill it
pkgname=mate-menus
pkgver=0.0.0-1
pkgdesc="MATE menu specifications"
#depends="glib2, python2"
# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf ${pkgname}.tar.gz
	# entramos a la carpeta
	cd ${pkgname}

	patch -Np0 -i "$srcdir/menus.patch"

	PYTHON=/usr/bin/python2 ./configure \
		--prefix=/usr --sysconfdir=/etc \
		--localstatedir=/var  --disable-static
	make
	make DESTDIR="${pkgdir}" install
}

# esto incluye la parte que se repite en la mayoria de los builds
. ../common
