#!/bin/bash

# fill it
pkgname=libmateweather
pkgver=2011.10.29
pkgrel=1
pkgdesc="Provides access to weather information from the net"
depends=('libsoup-dev')
#"mate-conf, mate-icon-theme"
# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf download
	# entramos a la carpeta
	cd ${pkgname}

	libtoolize --force || return 1
	gtkdocize || return 1
	aclocal || return 1
	autoconf || return 1
	automake || return 1
	./configure --prefix=/usr --sysconfdir=/etc \
		--localstatedir=/var --disable-static \
		--enable-locations-compression || return 1
	make || return 1

	make MATECONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=1 DESTDIR="${pkgdir}" install || return 1

	install -m755 -d "${pkgdir}/usr/share/mateconf/schemas"
	mateconf-merge-schema "${pkgdir}/usr/share/mateconf/schemas/${pkgname}.schemas" --domain libmateweather ${pkgdir}/etc/mateconf/schemas/*.schemas || return 1
	rm -f ${pkgdir}/etc/mateconf/schemas/*.schemas
}

# esto incluye la parte que se repite en la mayoria de los builds
. /usr/share/mate-doc-utils/mate-debian.sh
