#!/bin/bash

# fill it
pkgname=mate-corba
pkgver=2011.9.27
pkgrel=1
pkgdesc="Thin and fast CORBA ORB"
makedepends=('libglib2.0-dev' 'libidl-dev')

# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf download
	# entramos a la carpeta
	cd ${pkgname}

	./configure --prefix=/usr --disable-static
	make
	make DESTDIR="${pkgdir}" install
}

# esto incluye la parte que se repite en la mayoria de los builds
. /usr/share/mate-doc-utils/mate-debian.sh
