#!/bin/bash

# fill it
pkgname=mate-corba
pkgver=2011.10.29
pkgrel=1
pkgdesc="Thin and fast CORBA ORB"
depends=('libc6' 'libglib2.0-0' 'libidl0')
makedepends=('libglib2.0-dev' 'libidl-dev' 'pkg-config' 'cdbs' 'debhelper' 'docbook-xsl' 'gtk-doc-tools')

    
conflicts=('libmatecorba-dev')
provides=('libmatecorba-dev')

# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf download
	# entramos a la carpeta
	cd ${pkgname}

	./configure --prefix=/usr --disable-static || return 1
	make || return 1
	make DESTDIR="${pkgdir}" install || return 1
}

# esto incluye la parte que se repite en la mayoria de los builds
. /usr/share/mate-doc-utils/mate-debian.sh
