#!/bin/bash

# fill it
pkgname=libmatenotify
pkgver=2011.10.29
pkgrel=1
pkgdesc="Desktop notification library"
#depends="gdk-pixbuf2"
# editar esta funcion!
build() {
	cd $pkgsrc
	# descomprimir
	tar xvzf download
	# entramos a la carpeta
	cd ${pkgname}

	./configure --prefix=/usr --disable-static || return 1
	make || return 1
	make DESTDIR="${pkgdir}" install || return 1
}

# esto incluye la parte que se repite en la mayoria de los builds
. /usr/share/mate-doc-utils/mate-debian.sh
